import { useState } from 'react'
import { useAnimation } from 'framer-motion'
import { motion } from 'framer-motion'
import ColorForm from '../components/ColorForm/index'
import ColorList from '../components/ColorList/index'
import { generateColorSchemes } from '../lib/color-schemes'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Link from 'next/link'

export default function Index() {
  const [color, setColor] = useState(null)
  const [colorSchemes, setColorSchemes] = useState(null)
  const animation = useAnimation()

  const handleColorChange = (color) => {
    setColor(color)
    setColorSchemes(generateColorSchemes(color))
    animation.start({
      opacity: 1,
      x: 0,
      transition: { duration: 0.5 },
    })
  }

  return (
    <div className={styles.container}>
    <Head>
      <title>Palette 🎨</title>
      <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="128x128" href="icon.png" />
        <link rel="icon" sizes="192x192" href="icon.png" />
    </Head>

    <main className={styles.main}>
    <ColorForm onColorChange={handleColorChange} />
      {colorSchemes && (
        <motion.div animate={animation} initial={{ opacity: 0 }}>
          <ColorList colorSchemes={colorSchemes} />
        </motion.div>
      )}
      </main>


    <div className={styles.footerWrapper}>
    <footer className={styles.footer}>
      <p><span><Link href='/'>Palette</Link></span> by <a href="https://www.robinn.io/"
      target="_blank"
      rel="noopener noreferrer"
      >Robin Naghshbandi <span className={styles.pass}>🎨</span></a></p>
      <br/>
      <a className={styles.source} href="https://github.com/robbandi/Palette"
      target="_blank"
      rel="noopener noreferrer"
      >View source on GitHub</a>
    </footer> 
    </div>
  </div>
  )
}